name: Tweet to @TechLingoFYI

on:
  schedule:
    - cron:  '15 14 * * 1,3,5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - run: pip install -r requirements.txt

    - run: make tweet
